services:

  paytrack:
    build: .
    container_name: paytrack 
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    working_dir: /app
    volumes:
      - ./src:/app/src 
      - ./tests:/app/tests
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock 

    environment:
      UV_LINK_MODE: copy
      # PATH: "/app/.venv/bin:$PATH"
    networks:
      - app-network

    
  db:

    image: postgres:17.2
    container_name: paytrack_db
    restart: always
    environment:
      POSTGRES_USER: vronst
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: paytrack
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:


